### ISSUE TITLE
httpd24u-mod_security2

### ISSUE THREAD

**Issue by xarr** [iuscommunity/wishlist#64]
### What package do you want?

mod_security 2.9.1

### Why?

On CentOS 6, EPEL has release version 2.7.3-3.el6.
On CentOS 7, base has release version 2.7.3-5.el7.

In release version update 2.8.0-rc1 new libinjection-based XSS detection feature(s) were added.

In release version 2.9.1-rc1, the ability to generate audit logs in JSON format was added.

These new features would be useful to me.

### OS versions

My primary target OS is CentOS 7, although I'd welcome packaging on CentOS 6 as well.
I am not concerned with CentOS 5, due to its age.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by b-harper** [comment]
Hey @xarr,

Thanks for this request.  Generally, we only package new versions of software that are in EL as EPEL is the appropriate repository for software not in EL.  For EL 7, the decision for us to package mod_security is much more straight forward.  For EL 6, it would be better to reach out to the EPEL maintainer first.

Could you elaborate on the need for EL 6 packages?  We tend to avoid request like 'I don't have a need for foo, but I think it would be super neato if IUS packaged foo.'

**Comment by xarr** [comment]
Hi @b-harper,

Relative to the IUS project guidelines, I understand (and appreciate!) the careful approach in considering new software to package.

I still have some EL 6 instances in my fleet--access to a current mod_security package for EL 6 would absolutely allow me to delay upgrades to EL 7.

In short, a current mod_security package on EL 6 is **not** a must-have.

Should IUS agree to take on mod_security for EL 7, I could simply upgrade my age-ing EL 6 instances to EL 7 (which I arguably should be doing anyway).

Thanks!

**Comment by athmane** [comment]
Hi all,

EPEL/Fedora maintainer here.

If you are willing to help with testing, I could rebase EPEL6 package to the latest (same release found in Fedora branches), you could also use more up-to-date Copr repo for mod_security [1].

Not sure if it's a good idea to have pkg e-v-r in EPEL6 > EL7 (could break dist-upgrade). 

[1] https://copr.fedorainfracloud.org/coprs/athmane/mod_security/

**Comment by b-harper** [comment]
Hey @athmane,

Thanks for stopping by and sharing your thoughts.  You bring up a great point about EPEL6 > EL7 versioning.  Looking over EPEL's policies, I don't see any information about this situation.  Seeing that major OS upgrades are new with EL7 and the number of packages in older EPEL and newer EL are rare, I am not surprised there is not a policy for this situation.  

I think there is some wisdom in keeping the EPEL6 version <= EL7.

**Comment by xarr** [comment]
Hi @athmane,

Thanks for your reply.

The decision on whether or not to use Copr boils down to issue of trust and support.

I don't have much familiarity with Copr personally (feel free to correct any inaccuracies or mistaken assumptions), although it seems very much akin to Personal Package Archive (PPA), in that, anyone can supply sources and construct packages without the involvement of a third-party to vet the quality or integrity of the build in question.

More importantly, if/when a major bug or security incident occurs, which party would be responsible in owning the burden of upgrading packages in question? If using Copr-supplied packages, I imagine end-users would be beholden to the Copr repository maintainer of seemingly unknown availability.

@b-harper, correct me if I'm wrong but I believe IUS provides coverage for both of those concerns (trust and support).

Regarding EVR, I'm in agreement in keeping the EPEL6 version <= EL7, in the spirit of protecting end-user distribution upgrades. 

@athmane As such, I would **not** rebase the EPEL6 package.

Thank you.

**Comment by b-harper** [comment]
Hey @xarr,

Thanks for sharing your thoughts.  If IUS has earned your trust, then I will take that as a compliment.  We stand on the shoulders of giants (Fedora contributors) and try to work with our community as much as possible. 

I have briefly looked at porting the Fedora SRPM (thanks @athmane) and the name of the package is something that would need to be decided, see iuscommunity-pkg/httpd24u#7.

**Comment by athmane** [comment]
Hi @b-harper , let me know if I can help you on longer term, I could send PR each time I update Fedora package (which are more up-to-date).

You may also consider adding mod_security core rules set mod_security_crs [1], I've git-master in Fedora but older in EPEL (master is stable now).

[1] http://pkgs.fedoraproject.org/cgit/rpms/mod_security_crs.git/tree/mod_security_crs.spec

**Comment by b-harper** [comment]
Hey @athmane,

Thanks for the offer to assist.  We currently track upstream releases with our [Version Tracker][0].  Once upstream pushes a new version, we update our packages and check if Fedora has made any changes that would apply to our packages.  Historical, only IUS Core Devs (currently @carlwgeorge  and myself) would make changes.  This practice started when we used [LaunchPad][1], where collaborations were much more cumbersome.  With the switch to GitHub,  we have seen only a few pull requests.  Given our work flow and release cycle of mod_security, I am not sure not that pull requests would be critical, but boy would they be welcomed.  

@xarr, would you use mod_security_crs if we looked into packaging it?  

-Ben
[0]: https://versiontracker.iuscommunity.org/packages/
[1]: https://launchpad.net/ius

**Comment by b-harper** [comment]
I have some initial packages built and hit the development repositories after tonight's automation run.  Please note, a decision still needs to be made about the package name.

**Comment by xarr** [comment]
@b-harper,

Re: mod_security_crs, absolutely.

**Comment by b-harper** [comment]
@xarr,

Thanks for that feedback.  I have been looking into mod_security_crs and I am not sure if packaging is the best method for distribution.  It is a list of rules, similar to anti-virus definitions or SpamAssassin rules.  Typically those applications don't use package management to update their rule set.  Looking over that [project's web site][0], I have yet to find any information on implementation.  The download link points to a tarball of the latest commit.  The [latest release][1] on their [GitHub page][2]  is over two years old.  

That being said, Fedora and EL7 does offer packages and not sure if IUS needs to package it too.   

[0]:  https://www.owasp.org/index.php/Category:OWASP_ModSecurity_Core_Rule_Set_Project
[1]: https://github.com/SpiderLabs/owasp-modsecurity-crs/releases
[2]: https://github.com/SpiderLabs/owasp-modsecurity-crs

**Comment by xarr** [comment]
@b-harper,

Thank you for your patience.

I have successfully tested the mod_security2u-2.9.1-1.ius.centos7.x86_64 package currently in ius-dev.

It works perfectly.

Regarding the package naming, I'd prefer if the name included the branch version, for instance, mod_security**29**u. I see that a similar convention is used for IUS redis packages. Any reason we can't employ the same technique here?

Regarding 'owasp-modsecurity-crs' rule set(s), I don't believe it's necessary for IUS to package this-- at least not at this time. In terms of my deployment work-flow, I envision myself continuing to pull the master tarball directly from the github project page.

Once the naming is nailed down (preference of **29**u), I see no reason to not graduate this package into **ius-testing**.

Thanks.

**Comment by b-harper** [comment]
Hey @xarr,

Thanks for testing and glad to hear it is working great.  

I regards to naming convention, the number is determined when the upstream introduces changes that could cause breakage.  Take PHP as example, this happens at the second octet of the version number.  There could be breakage from upgrading from PHP 5.5 to 5.6.  Thus we package php55u and php56u separately, so manually action would be needed to upgrade from PHP 5.5 to 5.6.  Most of the application we package are like PHP, thus most of our package named like foo25u.

Looking over the mod_security documentation,  it is not super clear where they could  introduce changes that could cause breakage.  The best I could find was information about [upgrading from 1.x to 2.x][0].  

@xarr or @athmane, would you happen to have more definitive about mod_security versioning?

[0]: https://github.com/SpiderLabs/ModSecurity/wiki/ModSecurity-Frequently-Asked-Questions-(FAQ)#Whats_new_in_ModSecurity_and_why_should_I_upgrade_if_I_am_already_using_ModSecurity_1x/

**Comment by xarr** [comment]
@b-harper,

The [current available documentation](https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity) suggests the move from 2.x to 3.x may be fairly disruptive ("_complete rewrite of the ModSecurity platform_")--it appears mod_security 3.x development has moved toward "decoupling" from Apache--I'd say this in an of itself constitutes a rather significant architectural shift.

In the move from 1.x to 2.x, among other things, it was necessary for consumers to manually update/translate their existing owasp-modsecurity-crs rule set(s). I would not be surprised to learn that users will need to perform a similar transition in moving to 3.x.

In light of this, I would imagine this would justify that a 3.x release be packaged uniquely, e.g. mod_security**3u**.

Beyond that, I'm not privy to any specifics regarding the project's development practices, as they relate to versioning.

Finally, thank you for your clarification on IUS practices--mod_security**2u** works for me.

**Comment by b-harper** [comment]
Hey @xarr,

Thanks for the feedback.  Since it has been awhile since I first created this package, I was reviewing our initial IRC conversion, this issue and the package itself.   In IRC, you mentioned that this request was for stock httpd and not our httpd24u package.  Just want to make sure that is clear.

The initial package is built against stock httpd, but there is nothing in place to prevent the package being installed with httpd24u.  While mod_security built against stock httpd might just work with httpd24u, I am concerned it could break at some point.  I will look to get some updated packages built soon to prevent httpd24u and mod_security2u from being installed at the same time.

-Ben

**Comment by 0x00C0FFEE** [comment]
@b-harper,

Glad I was able to catch you on IRC--indeed, my original request was for the stock httpd package in EL7.

As we discussed, there was concern regarding the proposed mod_security2u package currently linking against the stock libapr. The httpd24u package currently links against your own libapr15u. 

As such, to ensure project consistency, the idea to mandate httpd24u with mod_security2u and restructure the package accordingly as **httpd24u-mod_security2** (supplementing existing httpd24u packages).

This idea works for me and I welcome a new round of testing once the proposed **httpd24u-mod_security2** lands in ius-dev.

Thanks for all your hard work on this one.

**Comment by xarr** [comment]
@b-harper,

Glad I was able to catch you on IRC--indeed, my original request was for the stock httpd package in EL7.

As we discussed, there was concern regarding the proposed mod_security2u package currently linking against the stock libapr. The httpd24u package currently links against your own libapr15u.

As such, to ensure project consistency, the idea to mandate httpd24u with mod_security2u and restructure the package accordingly as httpd24u-mod_security2 (supplementing existing httpd24u packages).

This idea works for me and I welcome a new round of testing once the proposed httpd24u-mod_security2 lands in ius-dev.

Thanks for all your hard work on this one.

**Comment by b-harper** [comment]
Hey @xarr and @athmane,

I am curious your thoughts about mlogc.   This sub-package is included in EPEL 6 and Fedora, but is not in EL7.  The Fedora SRPM has if/then logic that matches.  Is this a must have?

Since the request has changed from stock httpd to httpd24, it would make sense to build httpd24u-mod_security2 for all platforms we build httpd24u(EL6 and EL7).  Ideally, the decision about mlogc should be the same for EL6 and EL7.


-Ben

**Comment by athmane** [comment]
Hi @b-harper , IMHO, it's better to include mlogc, it usually needed for fancy loging in 3rd party applications (eg: mod_security console).

IIRC, the if logic was added by RH when they branched the package from Fedora. I included it in EPEL6 because I got requests from the community.

**Comment by b-harper** [comment]
@athmane,  Any ideas why it was not included in EL7?

**Comment by athmane** [comment]
if logic was added at the same time with excluding mod_security_crs-extra (Supplementary mod_security rules), jugging by that, I'm guessing they did want to support those extra bits (by support, I mean customer support).

**Comment by carlwgeorge** [comment]
I went ahead and enabled the mlogc subpackage for all releases.

Initial builds of httpd24u-mod_security2 have been completed and will move to the testing repositories during tonight's automation.

Note to self:
The mlogc component won't build on EL 6.6 because of some missing enum values in curl.  This doesn't affect EL 6.7 and newer.
```
mlogc.c:1281: error: 'CURL_SSLVERSION_TLSv1_0' undeclared (first use in this function)
mlogc.c:1284: error: 'CURL_SSLVERSION_TLSv1_1' undeclared (first use in this function)
mlogc.c:1287: error: 'CURL_SSLVERSION_TLSv1_2' undeclared (first use in this function)
```

**Comment by xarr** [comment]
I have tested httpd24u-mod_security2 (_ius-testing_)--looks good!

I will continue to monitor.

Thanks.

**Comment by carlwgeorge** [comment]
Thanks for the feedback @xarr.  I'll go ahead and tag this package to move to the stable repositories.  If you have any issues in the future you can report them directly on the [httpd24u-mod_security2 issues page](https://github.com/iuscommunity-pkg/httpd24u-mod_security2/issues).

Thanks for participating in IUS!
